package selenium_Basic_Program;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.edge.EdgeDriver;
public class Rewards
{
	public static void main(String[] args) throws InterruptedException
	{
		System.setProperty("webdriver.Edge.driver","E:\\Software Testing\\Jarfile\\Eclipse Program\\Selenium_ST\\msedgedriver.exe");
		WebDriver driver=new EdgeDriver();
		driver.manage().window().maximize();
		driver.get("https://www.bing.com/?scope=web&cc=IN&FORM=ANSPH1&pc=U531&wlexpsignin=1");
		WebElement searchBox1 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter.click();
		Thread.sleep(9000);
		searchBox1.sendKeys("A");
		enter.click();
		Thread.sleep(2000);
		driver.navigate().to("https://www.bing.com/?scope=web&cc=IN&FORM=ANSPH1&pc=U531&wlexpsignin=1");
		driver.navigate().refresh();
		WebElement searchBox2 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter1 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter1.click();
		searchBox2.sendKeys("B");
		enter1.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox3 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter2 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter2.click();
		searchBox3.sendKeys("C");
		enter2.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox4 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter3 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter3.click();
		searchBox4.sendKeys("D");
		enter3.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox5 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter4 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter4.click();
		searchBox5.sendKeys("E");
		enter4.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox6 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter5 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter5.click();
		searchBox6.sendKeys("F");
		enter5.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox7 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter6 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter6.click();
		searchBox7.sendKeys("G");
		enter6.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox8 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter7 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter7.click();
		searchBox8.sendKeys("H");
		enter7.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox9 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter8 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter8.click();
		searchBox9.sendKeys("I");
		enter8.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox10 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter9 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter9.click();
		searchBox10.sendKeys("J");
		enter9.click();
	    Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox11 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter10 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter10.click();
		searchBox11.sendKeys("K");
		enter10.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox12 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter11 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter11.click();
		searchBox12.sendKeys("L");
		enter11.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox13 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter12 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter12.click();
		searchBox13.sendKeys("M");
		enter12.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox14 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter13 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter13.click();
		searchBox14.sendKeys("N");
		enter13.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox15 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter14 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter14.click();
		searchBox15.sendKeys("O");
		enter14.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox16 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter15 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter15.click();
		searchBox16.sendKeys("P");
		enter15.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox17 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter16 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter16.click();
		searchBox17.sendKeys("Q");
		enter16.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox18 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter17 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter17.click();
		searchBox18.sendKeys("R");
		enter17.click();
	    Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox19 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter18 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter18.click();
		searchBox19.sendKeys("S");
		enter18.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox20 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter19 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter19.click();
		searchBox20.sendKeys("T");
		enter19.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox21 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter20 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter20.click();
		searchBox21.sendKeys("U");
		enter20.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox22 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter21 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter21.click();
		searchBox22.sendKeys("V");
		enter21.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox23 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter22 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter22.click();
		searchBox23.sendKeys("W");
		enter22.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox24 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter23 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter23.click();
		searchBox24.sendKeys("X");
		enter23.click();
		Thread.sleep(2000);
		driver.navigate().back();
		WebElement searchBox25 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter24 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter24.click();
		searchBox25.sendKeys("Y");
		enter24.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox26 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter25 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter25.click();
		searchBox26.sendKeys("Z");
		enter25.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox27 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter26 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter26.click();
		searchBox27.sendKeys("zaaaaaaaaaaaaaaaaaaaaaa");
		enter26.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox28 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter27 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter27.click();
		searchBox28.sendKeys("zbbbbbbbbbbbbbbbb");
		enter27.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox29 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter28 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter28.click();
		searchBox29.sendKeys("zccccccccccccccccc");
		enter28.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox30 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter29 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter29.click();
		searchBox30.sendKeys("zdddddddddddddddddd");
		enter29.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox31 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter30 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter30.click();
		searchBox31.sendKeys("zeeeeeeeeeeeeeeeee");
		enter30.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox32 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter31 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter31.click();
		searchBox32.sendKeys("zffffffffffffffffff");
		enter31.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox33 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter32 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter32.click();
		searchBox33.sendKeys("zgggggggggggggggggg");
		enter32.click();
		Thread.sleep(2000);
		driver.navigate().back();
		driver.navigate().refresh();
		WebElement searchBox34 = driver.findElement(By.xpath("//textarea[@type='search']"));
		WebElement enter33 = driver.findElement(By.xpath("//label[@id='search_icon']"));
		enter33.click();
		searchBox34.sendKeys("zhhhhhhhhhhhhhhhhhhhh");
		enter33.click();
		Thread.sleep(5000);
		driver.close();
	}
}
